config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get 'store/index'

get 'admin' => 'admin#index'

controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
end

resources :products do
  get :who_bought, on: :member
end

root :to => 'store#index', :as => 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= content_tag :body, class: controller.controller_name do %>
<div id="banner">
  <%= image_tag("logo.png") %>
  <%= @page_title || "Pragmatic Bookshelf" %>
</div>
  <div id="columns">
  <div id="side">
    <ul>
	<li><a href="http://localhost:3000">Home</a></li>
	<li><a href="http://localhost:3000/products">Products</a></li>
	<li><a href="http://www..../news">News</a></li>
	<li><a href="http://www..../contact">Contact</a></li>
    </ul>



<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
  <%= render @cart %>
<% end %>
<% if session[:user_id] %>
  <ul>
  <li><%= link_to 'Orders',   orders_path   %></li>
  <li><%= link_to 'Products', products_path %></li>
  <li><%= link_to 'Users',    users_path    %></li>
  </ul>
  <%= button_to 'Logout', logout_path, :method => :delete   %>
<% end %>
<br />
	<div id="time">	
	<%= Time.now %>
	</div>
  </div>
  <div id="main">
    <%= yield %>
  </div>
</div>
<% end %>
</body>
</html>